services:
  devsu-customer:
    image: daviduyaguarij/devsu-customer:latest
    container_name: devsu-customer
    env_file:
      - src/PersonCustomer/Devsu.PersonCustomer.Api/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "5046:8080"

  devsu-account:
    image: daviduyaguarij/devsu-account:latest
    container_name: devsu-account
    env_file:
      - src/AccountMovement/Devsu.AccountMovement.Api/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "8080"
      Services__PersonCustomer__BaseUrl: http://devsu-customer:8080
    ports:
      - "5004:8080"
    depends_on:
      - devsu-customer
